package com.example.famdif_final;

public enum FragmentName {
    INDEX, SEARCH, SEARCH_RESULT_DETAILS, SIGN_IN, LOG_IN, ABOUT_US, HOME, SUGGESTIONS,
    MY_SUGGESTIONS, RATE_SHOP, RATE_SHOP_RESULT, VIEW_SUGGESTIONS, VIEW_SUGGESTIONS_RESULT,
    ADD_SHOP, EDIT_SHOP,DELETE_USER, MAP, LIST_USUARIOS_BORRAR

}
