package com.example.famdif_final;

public enum FragmentName {
    INDEX, SEARCH, SEARCH_RESULT, SEARCH_RESULT_DETAILS, SIGN_IN, LOG_IN, ABOUT_US, HOME, SUGGESTIONS,
    MY_SUGGESTIONS, RATE_SHOP, RATE_SHOP_RESULT, VIEW_SUGGESTIONS, VIEW_SUGGESTIONS_RESULT,
    ADD_SHOP, EDIT_SHOP, EDIT_SHOP_FILTER, EDIT_SHOP_RESULT, DELETE_SHOP, DELETE_SHOP_RESULT,
    DELETE_USER, DELETE_USER_RESULT, MAP, LIST_USUARIOS_BORRAR

}
